services:
  web:
    image: ghcr.io/benjino16/ai-tomator:latest
    ports:
      - "8000:8000"
    environment:
      DB_PATH: /data/db/database.db
      STORAGE_DIR: /data/storage
    volumes:
      - db-data:/data/db
      - storage-data:/data/storage

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  db-data:
  storage-data:
