services:
  web:
    image: ghcr.io/benjino16/ai-tomator:latest
    ports:
      - "8000:8000"
    environment:
      DB_PATH: /data/db/database.db
      STORAGE_DIR: /data/storage
      #JWT Authentication Config
      SECURE_COOKIES: true #Set to false to allow JWT authentication over HTTP (not secure!)
      ACCESS_TOKEN_EXPIRE_MINUTES: 1440 # Time in minutes until the client has to log in again
      JWT_ENCRYPTION_KEY: "CHANGE-THIS-TO-A-SECURE-KEY"

    volumes:
      - db-data:/data/db
      - storage-data:/data/storage

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  db-data:
  storage-data:
